version: "3.7"

services:
  api:
    depends_on:
      - db
      - migrate
    ports:
      - "127.0.0.1:5000:5000"
    build:
      dockerfile: ./api/Dockerfile
      context: .
    volumes:
      - ./api:/app
    environment:
      - DB_STRING=postgresql://postgres:test@db:5432/postgres

  migrate:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    environment:
      - DB_STRING=postgresql://postgres:test@db:5432/postgres
    command: sh -c "alembic revision --autogenerate -m 'initial migration' && alembic upgrade head"
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    image: postgres:14.5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
  pytest:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    command: sh -c "pytest"
    volumes:
      - ./api:/app
    environment:

        - DB_STRING=postgresql://postgres:test@db:5432/postgres
        - PYTHONPATH=/app

    depends_on:
      - db
      - migrate
  pylint:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    command: sh -c "pylint user_repository.py"
    volumes:
      - ./api:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - pytest
  pyright:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    command: sh -c "pyright user_repository.py"
    volumes:
      - ./api:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - pylint
volumes:
  postgres-data:
