"""first migration

Revision ID: 0036c55fd9f6
Revises: 49eaf2ac81ba
Create Date: 2024-09-11 20:50:05.255789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0036c55fd9f6'
down_revision = '49eaf2ac81ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
