"""first migration

Revision ID: 005eb38fa2ec
Revises: b19f5cd9c53c
Create Date: 2024-09-12 00:38:21.630613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005eb38fa2ec'
down_revision = 'b19f5cd9c53c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
