"""first migration

Revision ID: 01d541383eeb
Revises: 6362adfe6ab8
Create Date: 2024-09-11 19:30:53.246032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d541383eeb'
down_revision = '6362adfe6ab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
