"""initial migration

Revision ID: 028b92ba96c7
Revises: b7080e0727f0
Create Date: 2024-09-08 18:54:49.398447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028b92ba96c7'
down_revision = 'b7080e0727f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
