"""first migration

Revision ID: 087f45bc2e28
Revises: 1feb50653430
Create Date: 2024-09-13 02:49:11.437219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087f45bc2e28'
down_revision = '1feb50653430'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
