"""initial migration

Revision ID: 0b7247e700de
Revises: 4d813db7d7e4
Create Date: 2024-09-10 01:02:57.865717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7247e700de'
down_revision = '4d813db7d7e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
