"""first migration

Revision ID: 0caaabe32191
Revises: a9ea6608e6dd
Create Date: 2024-09-12 00:42:08.810752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caaabe32191'
down_revision = 'a9ea6608e6dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
