"""first migration

Revision ID: 0f07b5f9a04c
Revises: 0036c55fd9f6
Create Date: 2024-09-11 20:55:04.726929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f07b5f9a04c'
down_revision = '0036c55fd9f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
