"""initial migration

Revision ID: 125d2e65d8e2
Revises: 8312ab47ebc4
Create Date: 2024-09-10 16:15:49.043080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125d2e65d8e2'
down_revision = '8312ab47ebc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
