"""first migration

Revision ID: 134728fd4626
Revises: 2bdc06fcf2a9
Create Date: 2024-09-11 19:26:40.123153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134728fd4626'
down_revision = '2bdc06fcf2a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
