"""first migration

Revision ID: 14889097efb1
Revises: b595628e84a7
Create Date: 2024-09-12 00:18:27.719908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14889097efb1'
down_revision = 'b595628e84a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
