"""initial migration

Revision ID: 14aa860fa6a3
Revises: 39fa4e881c3c
Create Date: 2024-09-10 17:27:03.697056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14aa860fa6a3'
down_revision = '39fa4e881c3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
