"""first migration

Revision ID: 154d07057bb4
Revises: d45d63d90599
Create Date: 2024-09-12 00:11:34.858031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154d07057bb4'
down_revision = 'd45d63d90599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
