"""initial migration

Revision ID: 21e03b59106e
Revises: 2c2f73f26d83
Create Date: 2024-09-10 00:39:49.467745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e03b59106e'
down_revision = '2c2f73f26d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
