"""initial migration

Revision ID: 246848a3ffbb
Revises: 028b92ba96c7
Create Date: 2024-09-08 18:56:21.557263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246848a3ffbb'
down_revision = '028b92ba96c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
