"""initial migration

Revision ID: 2b61132678ce
Revises: 125d2e65d8e2
Create Date: 2024-09-10 17:02:45.020982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b61132678ce'
down_revision = '125d2e65d8e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
