"""initial migration

Revision ID: 2c2f73f26d83
Revises: 8cd635f8b7f7
Create Date: 2024-09-10 00:30:48.740132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2f73f26d83'
down_revision = '8cd635f8b7f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
