"""first migration

Revision ID: 383d444de29f
Revises: 0caaabe32191
Create Date: 2024-09-12 00:43:37.595219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383d444de29f'
down_revision = '0caaabe32191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
