"""initial migration

Revision ID: 39fa4e881c3c
Revises: 2b61132678ce
Create Date: 2024-09-10 17:03:20.253378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fa4e881c3c'
down_revision = '2b61132678ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
