"""first migration

Revision ID: 3fc840f13444
Revises: e9c0c3f91cff
Create Date: 2024-09-12 01:29:35.723525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc840f13444'
down_revision = 'e9c0c3f91cff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
