"""first migration

Revision ID: 49eaf2ac81ba
Revises: a8f308230152
Create Date: 2024-09-11 20:45:53.847040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49eaf2ac81ba'
down_revision = 'a8f308230152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
