"""first migration

Revision ID: 4d1489cd6744
Revises: 7abe6b1f2a33
Create Date: 2024-09-11 20:23:45.222442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d1489cd6744'
down_revision = '7abe6b1f2a33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
