"""initial migration

Revision ID: 4d813db7d7e4
Revises: c0f35a058ac6
Create Date: 2024-09-10 00:58:50.040659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d813db7d7e4'
down_revision = 'c0f35a058ac6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
