"""initial migration

Revision ID: 62ca820d7740
Revises: f1030e378fc4
Create Date: 2024-09-10 00:16:59.419542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ca820d7740'
down_revision = 'f1030e378fc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
