"""first migration

Revision ID: 6362adfe6ab8
Revises: 134728fd4626
Create Date: 2024-09-11 19:29:37.726262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6362adfe6ab8'
down_revision = '134728fd4626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
