"""initial migration

Revision ID: 67495f0bffbf
Revises: 49bcc9e45ca2
Create Date: 2024-09-10 00:51:48.137114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67495f0bffbf'
down_revision = '49bcc9e45ca2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
