"""initial migration

Revision ID: 67590b3e5bdc
Revises: 246848a3ffbb
Create Date: 2024-09-08 19:18:59.572081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67590b3e5bdc'
down_revision = '246848a3ffbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
