"""first migration

Revision ID: 761cf5d4b85d
Revises: 154d07057bb4
Create Date: 2024-09-12 00:12:31.253242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761cf5d4b85d'
down_revision = '154d07057bb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
