"""first migration

Revision ID: 7abe6b1f2a33
Revises: ddcbc18ad732
Create Date: 2024-09-11 20:16:30.825144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abe6b1f2a33'
down_revision = 'ddcbc18ad732'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
