"""initial migration

Revision ID: 7e0e99a33e6b
Revises: fccfdb9eaa5a
Create Date: 2024-09-10 00:18:00.791182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0e99a33e6b'
down_revision = 'fccfdb9eaa5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
