"""initial migration

Revision ID: 8312ab47ebc4
Revises: a5cc25d594f7
Create Date: 2024-09-10 01:13:36.664565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8312ab47ebc4'
down_revision = 'a5cc25d594f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
