"""first migration

Revision ID: 88c358b245ed
Revises: 0f07b5f9a04c
Create Date: 2024-09-11 20:58:55.484011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c358b245ed'
down_revision = '0f07b5f9a04c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
