"""first migration

Revision ID: 8a44155632e5
Revises: fab154a6a941
Create Date: 2024-09-12 01:03:03.280995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a44155632e5'
down_revision = 'fab154a6a941'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
