"""initial migration

Revision ID: 8cd635f8b7f7
Revises: c7156ba4b627
Create Date: 2024-09-10 00:29:12.728869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd635f8b7f7'
down_revision = 'c7156ba4b627'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
