"""first migration

Revision ID: 9307a8bce628
Revises: d2e1e8992d93
Create Date: 2024-09-12 00:46:06.587168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9307a8bce628'
down_revision = 'd2e1e8992d93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
