"""first migration

Revision ID: 93721deeea98
Revises: 88c358b245ed
Create Date: 2024-09-11 21:02:53.411398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93721deeea98'
down_revision = '88c358b245ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
