"""first migration

Revision ID: 9395b9b436e3
Revises: d93df004cd84
Create Date: 2024-09-12 00:08:20.984830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9395b9b436e3'
down_revision = 'd93df004cd84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
