"""first migration

Revision ID: 97a0fcf2138d
Revises: c23814a853f5
Create Date: 2024-09-11 19:47:32.488009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a0fcf2138d'
down_revision = 'c23814a853f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
