"""first migration

Revision ID: a032eeaa800a
Revises: a25bb43d5dc9
Create Date: 2024-09-11 19:38:59.422523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a032eeaa800a'
down_revision = 'a25bb43d5dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
