"""first migration

Revision ID: a25bb43d5dc9
Revises: eb6b942d4908
Create Date: 2024-09-11 19:34:04.308778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25bb43d5dc9'
down_revision = 'eb6b942d4908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
