"""initial migration

Revision ID: a5cc25d594f7
Revises: 8da7bca1c8bc
Create Date: 2024-09-10 01:10:42.970125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cc25d594f7'
down_revision = '8da7bca1c8bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
