"""first migration

Revision ID: a9ea6608e6dd
Revises: 005eb38fa2ec
Create Date: 2024-09-12 00:40:18.121135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ea6608e6dd'
down_revision = '005eb38fa2ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
