"""initial migration

Revision ID: acffd1131b93
Revises: c61978957e2b
Create Date: 2024-09-10 00:20:54.735545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acffd1131b93'
down_revision = 'c61978957e2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
