"""first migration

Revision ID: b0e7f56a084e
Revises: 97a0fcf2138d
Create Date: 2024-09-11 19:54:31.784714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e7f56a084e'
down_revision = '97a0fcf2138d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
