"""first migration

Revision ID: b19f5cd9c53c
Revises: 14889097efb1
Create Date: 2024-09-12 00:36:51.575280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19f5cd9c53c'
down_revision = '14889097efb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
