"""first migration

Revision ID: b3eba4819697
Revises: f4ea76f445ae
Create Date: 2024-09-12 00:54:38.591780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3eba4819697'
down_revision = 'f4ea76f445ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
