"""first migration

Revision ID: b595628e84a7
Revises: 761cf5d4b85d
Create Date: 2024-09-12 00:13:48.902888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b595628e84a7'
down_revision = '761cf5d4b85d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
