"""initial migration

Revision ID: b7080e0727f0
Revises: 1210d59285df
Create Date: 2024-09-08 18:53:25.065774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7080e0727f0'
down_revision = '1210d59285df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
