"""initial migration

Revision ID: b8e9d3add5a8
Revises: 67590b3e5bdc
Create Date: 2024-09-08 19:32:21.332121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e9d3add5a8'
down_revision = '67590b3e5bdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('user', 'student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
