"""first migration

Revision ID: beef848fad55
Revises: b0e7f56a084e
Create Date: 2024-09-11 19:59:04.256752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beef848fad55'
down_revision = 'b0e7f56a084e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
