"""initial migration

Revision ID: c0f35a058ac6
Revises: 67495f0bffbf
Create Date: 2024-09-10 00:54:19.085200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f35a058ac6'
down_revision = '67495f0bffbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
