"""first migration

Revision ID: c23814a853f5
Revises: a032eeaa800a
Create Date: 2024-09-11 19:41:21.595765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23814a853f5'
down_revision = 'a032eeaa800a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
