"""initial migration

Revision ID: c61978957e2b
Revises: 7e0e99a33e6b
Create Date: 2024-09-10 00:20:08.644273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61978957e2b'
down_revision = '7e0e99a33e6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
