"""initial migration

Revision ID: c7156ba4b627
Revises: fdd5c9894606
Create Date: 2024-09-10 00:27:04.103135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7156ba4b627'
down_revision = 'fdd5c9894606'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
