"""first migration

Revision ID: ca36f7418d58
Revises: 7a4c29fb6505
Create Date: 2024-09-11 20:06:31.817008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca36f7418d58'
down_revision = '7a4c29fb6505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
