"""initial migration

Revision ID: cc62fe023f18
Revises: 21e03b59106e
Create Date: 2024-09-10 00:48:56.063606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc62fe023f18'
down_revision = '21e03b59106e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
