"""first migration

Revision ID: d2e1e8992d93
Revises: 383d444de29f
Create Date: 2024-09-12 00:44:31.483950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e1e8992d93'
down_revision = '383d444de29f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
