"""first migration

Revision ID: d45d63d90599
Revises: 9395b9b436e3
Create Date: 2024-09-12 00:09:29.624283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45d63d90599'
down_revision = '9395b9b436e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
