"""first migration

Revision ID: d955831a3f14
Revises: 6dbe51ecefc2
Create Date: 2024-09-11 20:11:55.456349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd955831a3f14'
down_revision = '6dbe51ecefc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
