"""first migration

Revision ID: ddcbc18ad732
Revises: d955831a3f14
Create Date: 2024-09-11 20:14:03.816614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcbc18ad732'
down_revision = 'd955831a3f14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
