"""first migration

Revision ID: e9c0c3f91cff
Revises: 8a44155632e5
Create Date: 2024-09-12 01:08:26.227462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c0c3f91cff'
down_revision = '8a44155632e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
