"""initial migration

Revision ID: f1030e378fc4
Revises: b8e9d3add5a8
Create Date: 2024-09-09 23:56:04.797728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1030e378fc4'
down_revision = 'b8e9d3add5a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
