"""first migration

Revision ID: f4ea76f445ae
Revises: 9307a8bce628
Create Date: 2024-09-12 00:48:59.352160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ea76f445ae'
down_revision = '9307a8bce628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
