"""initial migration

Revision ID: fdd5c9894606
Revises: cad7b135983e
Create Date: 2024-09-10 00:24:37.091787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd5c9894606'
down_revision = 'cad7b135983e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
